# -*- coding: utf-8 -*-
"""Customer Analytics & Order Insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LwXRPTJVjxzONXqUyNsgsde18YRT1Ecw
"""

import pandas as pd

# Load dataset
df = pd.read_csv("/content/Train.csv")

# Display first few rows
print(df.head())

# Check for missing values
print("Missing values in each column:")
print(df.isnull().sum())

# Convert relevant columns to string type
for col in ['Gender', 'Product_importance', 'Mode_of_Shipment', 'Warehouse_block']:
    df[col] = df[col].astype('string')

# Check for duplicate rows
print(f"Number of duplicate rows: {df.duplicated().sum()}")

# Statistical summary of numerical columns
print("Statistical summary:")
print(df.describe())

# Print unique values in categorical columns
for col in ['Gender', 'Product_importance', 'Mode_of_Shipment', 'Warehouse_block']:
    print(f"Unique values in '{col}': {df[col].unique()}")

# Frequency counts of categorical columns
print("Value counts for Product_importance:")
print(df['Product_importance'].value_counts())

print("Value counts for Mode_of_Shipment:")
print(df['Mode_of_Shipment'].value_counts())

# Average cost of product by Product Importance
avg_cost_by_importance = df.groupby('Product_importance')['Cost_of_the_Product'].mean()
print("Average Cost of Product by Product Importance:")
print(avg_cost_by_importance)

# Average on-time delivery rate by Mode of Shipment (percentage)
on_time_by_shipment = df.groupby('Mode_of_Shipment')['Reached.on.Time_Y.N'].mean() * 100
print("Average On-Time Delivery by Mode of Shipment (%):")
print(on_time_by_shipment)

# Average number of Customer Care Calls by delivery timeliness
calls_by_timeliness = df.groupby('Reached.on.Time_Y.N')['Customer_care_calls'].mean()
print("Average Customer Care Calls by Delivery Timeliness:")
print(calls_by_timeliness)

# Average Discount offered by Warehouse Block
avg_discount_by_warehouse = df.groupby('Warehouse_block')['Discount_offered'].mean()
print("Average Discount Offered by Warehouse Block:")
print(avg_discount_by_warehouse)

# Distribution of Customer Ratings
print("Customer Rating counts:")
print(df['Customer_rating'].value_counts())

# Average Customer Rating by Prior Purchases
rating_by_purchases = df.groupby('Prior_purchases')['Customer_rating'].mean()
print("Average Customer Rating by Prior Purchases:")
print(rating_by_purchases)

# Average Product Weight by Delivery Timeliness
weight_by_timeliness = df.groupby('Reached.on.Time_Y.N')['Weight_in_gms'].mean()
print("Average Product Weight by Delivery Timeliness:")
print(weight_by_timeliness)